/**:
  ros__parameters:
    PROJECT_NAME: "super_odometry"
    imu_topic: "/vectornav/imu"
    imu_sensor: "vectornav_enu"

    laser_topic: "/livox/lidar"
    lidar_sensor: "livox"
    use_imu_roll_pitch: true
    save_ply: false   # This can affect real-time performance; make sure you have enough memory for saving point cloud
    
    world_frame: "map"
    world_frame_rot: "map_rot"
    sensor_frame: "sensor"
    sensor_frame_rot: "sensor_rot"

    # TF frame names (from URDF) for extrinsic lookups
    imu_frame: "imu_link"
    lidar_frame: "lidar_link"
    base_frame: "base_link"
    yaw_ratio: 0.0

    imu_acc_x_limit: 2.0
    imu_acc_y_limit: 2.0
    imu_acc_z_limit: 2.0

    # Feature Extraction Params
    feature_extraction_node:
        scan_line: 4      # DONT TOUCH
        min_range: 0.2    #<!-- remove too closed points -->
        filter_point_size: 3
        voxel_leaf_size: 0.5

    # Laser Mapping Params
    laser_mapping_node:
        mapping_line_resolution: 0.1
        mapping_plane_resolution: 0.1
        max_iterations: 5
        max_surface_features: 4000
        auto_voxel_size: true

        # For localization mode
        localization_mode: false
        read_pose_file: false
        init_x: 0.0
        init_y: 0.0
        init_z: 0.0
        init_roll: 0.0
        init_pitch: 0.0
        init_yaw: 0.0 
    
    # DONT TOUCH
    # IMU Preintegration Params
    imu_preintegration_node:
        lidar_correction_noise: 0.04
        imu_dt: 0.005
        
        acc_n: 0.005          # accelerometer measurement noise standard deviation. #0.2
        gyr_n: 0.000005         # gyroscope measurement noise standard deviation.     #0.05
        acc_w: 0.005          # accelerometer bias random work noise standard deviation.  #0.02
        gyr_w: 0.000005       # gyroscope bias random work noise standard deviation.     #4.0e-5
        g_norm: 9.80511    # 0 means you need to provide both imu-camera and laser-camera extrinsic
