/**:
  ros__parameters:
    imu_topic: "/vectornav/imu_uncompensated"
    laser_topic: "/velodyne_points"
    sensor: "velodyne"
    use_imu_roll_pitch: false
    save_ply: false   # This can affect real-time performance; make sure you have enough memory for saving point cloud
    
    world_frame: "odom"
    world_frame_rot: "odom_rot"
    sensor_frame: "base_link"
    sensor_frame_rot: "base_link_rot"

    imu_acc_x_limit: 2.0
    imu_acc_y_limit: 2.0
    imu_acc_z_limit: 1.0

    # Feature Extraction Params
    feature_extraction_node:
        scan_line: 16 
        min_range: 0.2    #<!-- remove too closed points -->
        filter_point_size: 3
        voxel_leaf_size: 0.5
        lidar_mount_roll_deg: 0.0
        lidar_mount_pitch_deg: 0.0
        lidar_mount_yaw_deg: 0.0

    # Laser Mapping Params
    laser_mapping_node:
        mapping_line_resolution: 0.1
        mapping_plane_resolution: 0.2
        max_iterations: 5
        max_surface_features: 2000

        # For localization mode
        localization_mode: false
        read_pose_file: false
        init_x: 0.0
        init_y: 0.0
        init_z: 0.0
        init_roll: 0.0
        init_pitch: 0.0
        init_yaw: 0.0 

    # IMU Preintegration Params
    imu_preintegration_node:
        lidar_correction_noise: 0.01

        acc_n: 3.9939570888238808e-03          # accelerometer measurement noise standard deviation. #0.2
        gyr_n: 1.5636343949698187e-03         # gyroscope measurement noise standard deviation.     #0.05
        acc_w: 6.4356659353532566e-05          # accelerometer bias random work noise standard deviation.  #0.02
        gyr_w: 3.5640318696367613e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5
        g_norm: 9.80511    # 0 means you need to provide both imu-camera and laser-camera extrinsic

