%YAML:1.0

#Rotation from laser frame to imu frame, imu^R_laser
extrinsicRotation_imu_laser: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d  
  # data: [1., 0., 0.,
  #       0., 1., 0.,
  #       0., 0., 1.]
  # T^lidar_imu convention (right hand) spot imu
  # data: [ -0.9956921,  0.0910319,  0.0176171,
  #         0.0913757,  0.9956195,  0.0198054,
  #         -0.0157370,  0.0213299, -0.9996486 ]
  # T^lidar_imu convention (right hand) vectornav imu
  data: [ -0.2599915, -0.9654723, -0.0163586,
          0.9655964, -0.2598576, -0.0098737,
          0.0052819, -0.0183628,  0.9998174 ]


#Translation from laser frame to imu frame, imu^T_laser
extrinsicTranslation_imu_laser: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  # data: [0.0, 0.0, 0.0]
  # T^lidar_imu convention (right hand) spot imu
  # data: [0.079110, 0.043678, 0.067031]
  # T^lidar_imu convention (right hand) vectornav imu
  data: [-0.018992, -0.168931, -0.072069]
  # data: [0.265121, -0.41586, 0.045387]


imu_laser_rotation_offset: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [0.0, 0.0, 0.0] #[0.0, 0.5, 0.0]

yaw_ratio: 0.0
